### ISSUE TITLE
[FEATURE] Husky 세팅

### ISSUE THREAD

**Issue by ttaerrim** [boostcampwm2023/web17_morak#6]
## 이슈 설명
pre-commit에 필요한 Husky 세팅하기

## 체크 리스트
- [ ] 커밋 전 eslint 작동 확인
- [ ] 커밋 전 prettier 작동 확인
- [ ] 커밋 전 stylelint 작동 확인

**Comment by ttaerrim** [comment]
stylelint가 vanilla-extract에서 사용할 수 없기 때문에 제거하는 것이 좋을 것 같습니다. @LEEJW1953 @js43o

**Comment by LEEJW1953** [comment]
> stylelint가 vanilla-extract에서 사용할 수 없기 때문에 제거하는 것이 좋을 것 같습니다. @LEEJW1953 @js43o

동의합니다.

**Comment by js43o** [comment]
> stylelint가 vanilla-extract에서 사용할 수 없기 때문에 제거하는 것이 좋을 것 같습니다. @LEEJW1953 @js43o

저도 동의합니다.
+ 혹시 stylelint 제거하는김에 react-hook-form, FullCalendar도 같이 설치하는거 어떻게 생각하시나요?
